# Generated by Django 3.2 on 2021-05-07 20:45

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import site_2_process_instrument.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='enter description of the about us page.')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_location', models.CharField(help_text='Enter your <b>LOCATION</b> which will be display on contact form', max_length=100)),
                ('display_email', models.EmailField(help_text='Enter your <b>EMAIL</b> which will be display on contact form', max_length=254)),
                ('display_call', models.CharField(help_text='Enter your <b>PHONE_NUMBER</b> which will be display on contact form', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='HomeImageSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(help_text='Enter image you want to display on the home page slider ', storage=django.core.files.storage.FileSystemStorage(base_url='/media/my_sell/', location='/home/pulkit/practice/scienco-medical-instrument/media/my_sell/'), upload_to=site_2_process_instrument.models.image_directory_path)),
                ('image_description', models.CharField(help_text='Enter image description', max_length=250)),
                ('image_heading', models.CharField(help_text='Enter image Heading', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TechnicalStaff', models.IntegerField()),
                ('YearsOfExperience', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('NumberOfSatisfiedClient', models.IntegerField()),
                ('StatesCoveredInIndia', models.IntegerField(validators=[django.core.validators.MaxValueValidator(29)])),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentsParametersWise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter <b>Title of "InstrumentsParametersWise"</b> which is displyed on home page ', max_length=100)),
                ('description', models.CharField(help_text='Enter <b>Description of "Title of InstrumentsParametersWise"</b> which is displyed on home page ', max_length=500)),
                ('bootstrap_icons', models.CharField(help_text='<h4>do not play with this, this part is related to coding </h4>', max_length=100)),
            ],
        ),
    ]
