# Generated by Django 3.2 on 2021-05-05 15:04

import django.core.files.storage
from django.db import migrations, models
import site_2_process_instrument.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeImageSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/my_sell/', location='/home/sunil/workspace/pulkit/vikash/scienco-medical-instrument/media/my_sell/'), upload_to=site_2_process_instrument.models.image_directory_path)),
            ],
        ),
    ]
