# Generated by Django 3.2 on 2021-05-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_2_process_instrument', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_display',
            name='display_email',
            field=models.EmailField(max_length=254),
        ),
    ]
