# Generated by Django 3.2 on 2021-05-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_2_process_instrument', '0002_contactmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
