# Generated by Django 3.2 on 2021-05-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_2_process_instrument', '0002_alter_contact_display_display_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TechnicalStaff', models.CharField(max_length=50)),
                ('YearsOfExperience', models.CharField(max_length=50)),
                ('NumberOfSatisfiedClient', models.CharField(max_length=50)),
                ('StatesCoveredInIndia', models.CharField(max_length=50)),
            ],
        ),
    ]
