# Generated by Django 3.2 on 2021-05-05 18:41

import django.core.files.storage
from django.db import migrations, models
import site_2_process_instrument.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_2_process_instrument', '0003_alter_contactmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeimageslider',
            name='image',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/my_sell/', location='/home/pulkit/practice/scienco-medical-instrument/media/my_sell/'), upload_to=site_2_process_instrument.models.image_directory_path),
        ),
    ]
