# Generated by Django 3.2 on 2021-05-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_2_process_instrument', '0003_homepagedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagedata',
            name='NumberOfSatisfiedClient',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='homepagedata',
            name='StatesCoveredInIndia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='homepagedata',
            name='TechnicalStaff',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='homepagedata',
            name='YearsOfExperience',
            field=models.IntegerField(),
        ),
    ]
