# Generated by Django 3.2 on 2021-05-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_2_process_instrument', '0004_auto_20210507_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagedata',
            name='StatesCoveredInIndia',
            field=models.IntegerField(verbose_name=False),
        ),
    ]
