# Generated by Django 3.2 on 2021-05-07 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_2_process_instrument', '0005_alter_homepagedata_statescoveredinindia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagedata',
            name='StatesCoveredInIndia',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(29)]),
        ),
    ]
