# Generated by Django 3.2 on 2021-05-10 07:46

import django.core.files.storage
from django.db import migrations, models
import site_2_process_instrument.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_2_process_instrument', '0005_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(base_url='/media/my_sell/', location='/home/pulkit/practice/scienco-medical-instrument/media/my_sell/'), upload_to=site_2_process_instrument.models.image_directory_path),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Qualification',
            field=models.CharField(help_text='Enter your <b>Qualification</b> which will be display on blog', max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(help_text='Enter your <b>description</b> which will be display on blog', max_length=300),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(help_text='Enter your <b>name</b> which will be display on blog', max_length=50),
        ),
    ]
