# Generated by Django 3.2 on 2021-05-07 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_2_process_instrument', '0006_alter_homepagedata_statescoveredinindia'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentsParametersWise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='homepagedata',
            name='YearsOfExperience',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(29)]),
        ),
    ]
